# Generated by Django 4.1.3 on 2022-11-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameRank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerank1',
            old_name='genre',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='gamerank1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gamerank1',
            name='released',
        ),
        migrations.RemoveField(
            model_name='gamerank1',
            name='title',
        ),
    ]
