# Generated by Django 4.1.3 on 2022-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameRank', '0002_rename_genre_gamerank1_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerank1',
            old_name='rating',
            new_name='ranking',
        ),
    ]
