# Generated by Django 4.1.3 on 2022-11-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameRank', '0004_rename_user_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
