# Generated by Django 4.1.3 on 2022-11-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameRank', '0006_alter_gamerank1_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
